# -*- coding: utf-8 -*-
"""supermarket sales data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCz7pV1nxXN7OP0QhKeRdCvOqWrhxgNF
"""



from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
# Load CSV file
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/SuperMarket Analysis.csv.xls")

# Display first few rows
print(data.head())

#Extract Required Columns as NumPy Arrays
product_category = data["Product line"].values
quantity = data["Quantity"].values
unit_price = data["Unit price"].values
total_sales = data["Sales"].values
profit = data["gross income"].values
print(product_category)
print(quantity)
print(unit_price)
print(total_sales)
print(profit)

#Total and Average Sales Calculation
total_revenue = np.sum(total_sales)
average_sales = np.mean(total_sales)

print("Total Revenue:", total_revenue)
print("Average Sales:", average_sales)

#Indexing and Slicing
# First 10 sales records
print("First 10 Sales:", total_sales[:10])

# Last 5 profit records
print("Last 5 Profits:", profit[-5:])

#Statistical Operations
mean_sales = np.mean(total_sales)
median_sales = np.median(total_sales)
variance_sales = np.var(total_sales)
std_sales = np.std(total_sales)

print("Mean Sales:", mean_sales)
print("Median Sales:", median_sales)
print("Variance:", variance_sales)
print("Standard Deviation:", std_sales)

#Broadcasting (Revenue Calculation)
calculated_revenue = quantity * unit_price

print("Calculated Revenue (first 10):", calculated_revenue[:10])

#Vectorized Computation
# Profit percentage using vectorized operation
profit_percentage = (profit / total_sales) * 100

print("Profit Percentage (first 10):", profit_percentage[:10])

#Category-wise Sales Analysis
unique_categories = np.unique(product_category)

for category in unique_categories:
    category_sales = total_sales[product_category == category]
    print(f"{category} - Total Sales: {np.sum(category_sales)}")

#Interpretation of Results
highest_sale = np.max(total_sales)
lowest_sale = np.min(total_sales)

print("Highest Sale Value:", highest_sale)
print("Lowest Sale Value:", lowest_sale)